# Generated by Django 5.1.3 on 2024-11-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_admin', '0003_proveedor_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(max_length=255)),
                ('servCaninos', models.CharField(max_length=255)),
                ('servFelinos', models.CharField(max_length=255)),
                ('testimonios', models.CharField(max_length=255)),
            ],
        ),
    ]
