# Generated by Django 5.1.1 on 2024-11-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_admin', '0004_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='testimonios',
        ),
        migrations.AddField(
            model_name='menu',
            name='testimonio1',
            field=models.TextField(default='Testimonio predeterminado 1'),
        ),
        migrations.AddField(
            model_name='menu',
            name='testimonio2',
            field=models.TextField(default='Testimonio predeterminado 2'),
        ),
        migrations.AddField(
            model_name='menu',
            name='testimonio3',
            field=models.TextField(default='Testimonio predeterminado 3'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='servCaninos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='servFelinos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='subtitulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
