
# Generated by Django 5.1.3 on 2024-11-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_admin', '0005_remove_menu_testimonios_menu_testimonio1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='servCaninos',
            field=models.TextField(default='Baño, Corte de pelo, Corte de uñas, Consulta veterinaria, Vacunación, Desparasitación, Cirugía, Hospitalización, Pel'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='servFelinos',
            field=models.TextField(default='Baño, Corte de pelo, Corte de uñas, Consulta veterinaria, Vacunación, Desparasitación, Cirugía, Hospitalización, Pel'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='subtitulo',
            field=models.CharField(default='Nos dedicamos a cuidar a tus mascotas con mucho amor y profesionalismo.', max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='testimonio1',
            field=models.TextField(default='Excelente servicio, mi perro siempre está en buenas manos. Los veterinarios son muy atentos y profesionales. ¡Muy recomendados! - Laura G'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='testimonio2',
            field=models.TextField(default='Llevé a mi perro Logan stiven para una consulta y me dieron un trato increíble. Además, su tienda tiene todo lo necesario para su bienestar. ¡Volveré! - Carlos V.'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='testimonio3',
            field=models.TextField(default='Un lugar confiable para la salud de mis mascotas. El equipo siempre está dispuesto a ayudar y aconsejar. ¡Gracias por su dedicación! - Ana P.'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='titulo',
            field=models.CharField(default='Bienvenidos a la Clínica Veterinaria SONRISAS Y PATITAS', max_length=100),
        ),
    ]
