# Generated by Django 5.1.3 on 2024-11-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_admin', '0006_alter_menu_servcaninos_alter_menu_servfelinos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='catalogo',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='catalogo_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
